spring.application.name=historicdata

server.port=3000
server.forward-headers-strategy=native

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true